import type { Category } from "./types"

export const categories: Category[] = [
  {
    slug: "elektronik",
    name: "Elektronik & Technik",
    icon: "Smartphone",
    description: "Smartphone, PC, TV & mehr",
    subcategories: ["Smartphone-Reparatur", "PC-Hilfe", "TV & Audio", "Netzwerk & WLAN", "Smart Home"],
    takumiCount: 0,
    color: "#3b82f6",
  },
  {
    slug: "haus-garten",
    name: "Haus & Garten",
    icon: "Home",
    description: "Pflanzen, Gartenpflege, Reparatur",
    subcategories: ["Pflanzenpflege", "Gartengestaltung", "Hausreparatur", "Einrichtungsberatung", "Schadlingsbekampfung"],
    takumiCount: 0,
    color: "#22c55e",
  },
  {
    slug: "auto-rad-boot",
    name: "Auto, Rad & Boot",
    icon: "Car",
    description: "KFZ-Diagnose, Motorrad, Fahrrad",
    subcategories: ["KFZ-Diagnose", "Motorrad-Wartung", "Fahrrad-Reparatur", "Boot-Pflege", "Oldtimer-Beratung"],
    takumiCount: 0,
    color: "#ef4444",
  },
  {
    slug: "mode-beauty",
    name: "Mode & Beauty",
    icon: "Shirt",
    description: "Styling, Schneider, Schuster",
    subcategories: ["Stilberatung", "Schneiderarbeiten", "Schuhreparatur", "Kosmetik-Beratung", "Farbberatung"],
    takumiCount: 0,
    color: "#ec4899",
  },
  {
    slug: "familie-kind-baby",
    name: "Familie, Kind & Baby",
    icon: "Baby",
    description: "Erziehung, Babypflege, Beratung",
    subcategories: ["Erziehungsberatung", "Babypflege", "Lernhilfe Kinder", "Familienplanung", "Kinderbeschaftigung"],
    takumiCount: 0,
    color: "#f472b6",
  },
  {
    slug: "haustiere",
    name: "Haustiere",
    icon: "PawPrint",
    description: "Tiertraining, Pflege, Ernahrung",
    subcategories: ["Hundetraining", "Katzenpflege", "Aquaristik", "Vogelhaltung", "Tierernahrung"],
    takumiCount: 0,
    color: "#f59e0b",
  },
  {
    slug: "musik-film-buecher",
    name: "Musik, Film & Bucher",
    icon: "Music",
    description: "Instrument-Hilfe, Aufnahme, Beratung",
    subcategories: ["Gitarren-Setup", "Aufnahmetechnik", "Musiktheorie", "Filmschnitt", "Buchbinderei"],
    takumiCount: 0,
    color: "#8b5cf6",
  },
  {
    slug: "freizeit-hobby",
    name: "Freizeit, Hobby & Nachbarschaft",
    icon: "Palette",
    description: "Sport, Kochen, Handarbeit",
    subcategories: ["Kochen & Backen", "Handarbeit & Nahen", "Fotografie", "Sporttraining", "Gartnern"],
    takumiCount: 0,
    color: "#06b6d4",
  },
  {
    slug: "dienstleistungen",
    name: "Dienstleistungen",
    icon: "Briefcase",
    description: "Steuer, Recht, Handwerk-Beratung",
    subcategories: ["Steuerberatung", "Rechtsberatung", "Versicherung", "Finanzplanung", "Handwerk-Vermittlung"],
    takumiCount: 0,
    color: "#64748b",
  },
  {
    slug: "unterricht-kurse",
    name: "Unterricht & Kurse",
    icon: "GraduationCap",
    description: "Nachhilfe, Sprachen, IT-Kurse",
    subcategories: ["Mathe-Nachhilfe", "Sprachunterricht", "IT & Programmieren", "Musikunterricht", "Prufungsvorbereitung"],
    takumiCount: 0,
    color: "#0ea5e9",
  },
  {
    slug: "heimwerken",
    name: "Heimwerken & Renovierung",
    icon: "Wrench",
    description: "Elektrik, Sanitaer, Malerarbeiten",
    subcategories: ["Elektrik-Beratung", "Sanitaer-Hilfe", "Malerarbeiten", "Boden verlegen", "Trockenbau"],
    takumiCount: 0,
    color: "#d97706",
  },
]
