/**
 * Seed data for initial DB population via /api/takumis/seed.
 * This is NOT used by any frontend component -- only the admin seed endpoint.
 */
export const seedTakumis = [
  {
    name: "Stefan Berger",
    avatar: "SB",
    categorySlug: "elektronik",
    categoryName: "Elektronik & Technik",
    subcategory: "Smartphone-Reparatur",
    bio: "Zertifizierter Apple & Samsung Techniker mit uber 10 Jahren Erfahrung. Ich helfe dir bei allen Smartphone-Problemen -- von Display-Schaden bis Software-Fehlern.",
    rating: 4.9,
    reviewCount: 142,
    sessionCount: 318,
    responseTime: "< 2 Min",
    pricePerSession: 29,
    isLive: true,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-03-15",
  },
  {
    name: "Maria Schneider",
    avatar: "MS",
    categorySlug: "haus-garten",
    categoryName: "Haus & Garten",
    subcategory: "Pflanzenpflege",
    bio: "Gartenarchitektin und Pflanzenliebhaberin. Ob Zimmerpflanzen oder Gartengestaltung -- ich bringe dein Grun zum Bluhen. Spezialisiert auf nachhaltige Gartenkonzepte.",
    rating: 4.8,
    reviewCount: 89,
    sessionCount: 205,
    responseTime: "< 5 Min",
    pricePerSession: 25,
    isLive: true,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-01-20",
  },
  {
    name: "Klaus Richter",
    avatar: "KR",
    categorySlug: "auto-rad-boot",
    categoryName: "Auto, Rad & Boot",
    subcategory: "KFZ-Diagnose",
    bio: "KFZ-Meister seit 1998. Ich diagnostiziere dein Auto-Problem per Video -- spare dir die Werkstatt-Fahrt und erhalte eine ehrliche Einschatzung.",
    rating: 4.7,
    reviewCount: 67,
    sessionCount: 156,
    responseTime: "< 10 Min",
    pricePerSession: 35,
    isLive: false,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-05-10",
  },
  {
    name: "Lena Fischer",
    avatar: "LF",
    categorySlug: "mode-beauty",
    categoryName: "Mode & Beauty",
    subcategory: "Stilberatung",
    bio: "Fashion-Stylistin aus Berlin. Ich helfe dir, deinen perfekten Look zu finden -- vom Alltagsoutfit bis zum Event-Styling. Nachhaltig und individuell.",
    rating: 4.9,
    reviewCount: 112,
    sessionCount: 287,
    responseTime: "< 3 Min",
    pricePerSession: 29,
    isLive: true,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-02-08",
  },
  {
    name: "Thomas Wagner",
    avatar: "TW",
    categorySlug: "heimwerken",
    categoryName: "Heimwerken & Renovierung",
    subcategory: "Elektrik-Beratung",
    bio: "Elektromeister mit Fokus auf Heimwerker-Beratung. Ich zeige dir, was du selbst machen kannst und wann du einen Profi brauchst. Sicherheit geht vor!",
    rating: 4.6,
    reviewCount: 45,
    sessionCount: 98,
    responseTime: "< 8 Min",
    pricePerSession: 32,
    isLive: false,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-06-22",
  },
  {
    name: "Anna Braun",
    avatar: "AB",
    categorySlug: "unterricht-kurse",
    categoryName: "Unterricht & Kurse",
    subcategory: "Sprachunterricht",
    bio: "Zertifizierte DaF-Lehrerin und Ubersetzerin. Deutsch, Englisch und Spanisch fur alle Niveaus. Interaktiv, geduldig und mit viel Humor.",
    rating: 4.8,
    reviewCount: 95,
    sessionCount: 412,
    responseTime: "< 1 Min",
    pricePerSession: 22,
    isLive: true,
    isPro: false,
    verified: true,
    portfolio: [],
    joinedDate: "2023-11-05",
  },
  {
    name: "Markus Hoffmann",
    avatar: "MH",
    categorySlug: "dienstleistungen",
    categoryName: "Dienstleistungen",
    subcategory: "Steuerberatung",
    bio: "Steuerberater mit Schwerpunkt Kleinunternehmer und Freelancer. Ich erklare komplexe Steuerthemen einfach und helfe dir, bares Geld zu sparen.",
    rating: 4.9,
    reviewCount: 78,
    sessionCount: 189,
    responseTime: "< 5 Min",
    pricePerSession: 45,
    isLive: false,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-04-12",
  },
  {
    name: "Sandra Koch",
    avatar: "SK",
    categorySlug: "haustiere",
    categoryName: "Haustiere",
    subcategory: "Hundetraining",
    bio: "Zertifizierte Hundetrainerin mit Spezialisierung auf Verhaltenstherapie. Ich helfe dir und deinem Vierbeiner zu einer harmonischen Beziehung.",
    rating: 4.7,
    reviewCount: 56,
    sessionCount: 134,
    responseTime: "< 4 Min",
    pricePerSession: 28,
    isLive: true,
    isPro: false,
    verified: true,
    portfolio: [],
    joinedDate: "2024-07-01",
  },
  {
    name: "David Muller",
    avatar: "DM",
    categorySlug: "freizeit-hobby",
    categoryName: "Freizeit, Hobby & Nachbarschaft",
    subcategory: "Fotografie",
    bio: "Professioneller Fotograf mit Leidenschaft fur Portrats und Landschaften. Ich zeige dir, wie du mit jeder Kamera beeindruckende Fotos machst.",
    rating: 4.5,
    reviewCount: 34,
    sessionCount: 76,
    responseTime: "< 6 Min",
    pricePerSession: 26,
    isLive: false,
    isPro: false,
    verified: true,
    portfolio: [],
    joinedDate: "2024-08-18",
  },
  {
    name: "Julia Weber",
    avatar: "JW",
    categorySlug: "familie-kind-baby",
    categoryName: "Familie, Kind & Baby",
    subcategory: "Erziehungsberatung",
    bio: "Padagogin und Familienberaterin. Ich unterstutze Eltern mit alltagstauglichen Tipps fur ein liebevolles und konsequentes Miteinander.",
    rating: 4.8,
    reviewCount: 63,
    sessionCount: 147,
    responseTime: "< 3 Min",
    pricePerSession: 30,
    isLive: true,
    isPro: true,
    verified: true,
    portfolio: [],
    joinedDate: "2024-02-28",
  },
]
