/**
 * Kuratierte Lucide-Icon-Namen für die Kategorie-Pflege (Admin).
 * Muss mit lucide-react exportierten Namen übereinstimmen (PascalCase).
 */
export const TAXONOMY_ICON_KEYS = [
  "Briefcase",
  "Wrench",
  "Home",
  "Car",
  "Smartphone",
  "Palette",
  "Shirt",
  "Baby",
  "PawPrint",
  "Music",
  "GraduationCap",
  "Heart",
  "Star",
  "Zap",
  "Sun",
  "Moon",
  "Cloud",
  "Umbrella",
  "TreePine",
  "Flower2",
  "Coffee",
  "Utensils",
  "Dumbbell",
  "Bike",
  "Plane",
  "Ship",
  "Camera",
  "Video",
  "Mic",
  "Headphones",
  "BookOpen",
  "PenLine",
  "Calculator",
  "Landmark",
  "Scale",
  "Shield",
  "Stethoscope",
  "Pill",
  "Brain",
  "Lightbulb",
  "Cpu",
  "Wifi",
  "Gamepad2",
  "Paintbrush",
  "Scissors",
  "Hammer",
  "Plug",
  "Battery",
  "Thermometer",
  "Leaf",
  "Recycle",
  "Building2",
  "Store",
  "ShoppingBag",
  "Gift",
  "PartyPopper",
  "Trophy",
  "Medal",
  "Target",
  "Compass",
  "Map",
  "Globe",
  "Languages",
  "Users",
  "UserCircle",
  "Sparkles",
] as const

export type TaxonomyIconKey = (typeof TAXONOMY_ICON_KEYS)[number]

export function isValidTaxonomyIconKey(key: string): key is TaxonomyIconKey {
  return (TAXONOMY_ICON_KEYS as readonly string[]).includes(key)
}
